

stages:
  - stage: A
    pool:
     vmImage: ubuntu-latest
    displayName: "ubuntu"
    jobs:
      - job: Ajob
        pool:
          vmImage: windows-latest
        displayName: "this is windows"
      - job: JobB
  - stage: B
    jobs:
      - job: c
        steps:
          - script: "echo"